# Site settings
title: "darb.io - "
email: james@darb.io
description: "The website of darbio, a web developer and senior enterprise software 'architect' from Sydney, Australia."
baseurl: ""
url: "http://darb.io"
#paginate: 5
#paginate_path: "blog/page:num"
highlighter: pygments

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /blog/:categories/:year/:month/:day/:title/
